name: Telegram pm sender
on:
  push:
    branches: master
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
    - name: sending is comming
      uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        status: ${{ job.status }}
  echo:
  runs-on: ubuntu-latest
  steps:
  -name: echo matrix
  run: echo {{ matrix.os }}
